---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6-chef-12
    driver:
      box: opscode-centos-6.6
    provisioner:
      require_chef_omnibus: 12.2.1
  - name: centos-6.6-chef-11
    driver:
      box: opscode-centos-6.6
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: ubuntu-12.04-chef-12
    driver:
      box: opscode-ubuntu-12.04
    provisioner:
      require_chef_omnibus: 12.2.1
  - name: ubuntu-12.04-chef-11
    driver:
      box: opscode-ubuntu-12.04
    provisioner:
      require_chef_omnibus: 11.18.6

suites:
  - name: default
    run_list:
      - recipe[selinux::default]
      - recipe[selinux_policy_test::default]
    attributes:
