---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6-chef-12
    driver:
      box: opscode-centos-6.6
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
    provisioner:
      require_chef_omnibus: 12.2.1
  - name: centos-6.6-chef-11
    driver:
      box: opscode-centos-6.6
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
    provisioner:
      require_chef_omnibus: 11.18.6

suites:
  - name: default
    run_list:
      - recipe[selinux::default]
      - recipe[selinux_policy_test::default]
    attributes:
